# permissions for end users to edit minecraftclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minecraftcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shulker
    app.kubernetes.io/part-of: shulker
    app.kubernetes.io/managed-by: kustomize
  name: minecraftcluster-editor-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters/status
  verbs:
  - get
