---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftserverdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftserverdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - proxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments/status
  verbs:
  - get
  - patch
  - update
