apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  labels:
    app.kubernetes.io/name: minecraftcluster
    app.kubernetes.io/instance: minecraftcluster-sample
    app.kubernetes.io/part-of: shulker
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: shulker
  name: minecraftcluster-sample
spec:
  # TODO(user): Add fields here
