name: deploy

on:
  push:
    branches:
      - main
      - rework

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        app:
          - shulker-operator
          - shulker-drainer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/iamblueslime/${{ matrix.app }}
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=sha
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: cmd/${{ matrix.app }}
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
